# Generated by Django 4.2 on 2025-06-23 17:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="car code"
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="car number plate",
                    ),
                ),
                (
                    "plate_character",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="car plate character",
                    ),
                ),
                (
                    "plate_color",
                    models.CharField(
                        choices=[
                            ("Red", "Red"),
                            ("Blue", "Blue"),
                            ("Orange", "Orange"),
                            ("Yellow", "Yellow"),
                            ("Green", "Green"),
                            ("Gold", "Gold"),
                        ],
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(max_length=10)),
                ("license_expiration_date", models.DateField(blank=True, null=True)),
                ("examination_date", models.DateField(blank=True, null=True)),
                ("model_year", models.IntegerField()),
                ("brand", models.CharField(max_length=25)),
                ("is_with_odometer", models.BooleanField()),
                ("tank_capacity", models.IntegerField()),
                ("permitted_fuel_amount", models.IntegerField()),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("Diesel", "Diesel"),
                            ("Solar", "Solar"),
                            ("Gasoline", "Gasoline"),
                            ("Natural_Gas", "Natural Gas"),
                            ("Electric", "Electric"),
                            ("Hydrogen", "Hydrogen"),
                        ],
                        max_length=20,
                    ),
                ),
                ("oil_type", models.CharField(blank=True, max_length=20, null=True)),
                ("fuel_consumption_rate", models.IntegerField(default=0)),
                ("number_of_fuelings_per_day", models.IntegerField()),
                ("number_of_washes_per_month", models.IntegerField()),
                ("fuel_allowed_days", models.JSONField(blank=True, default=list)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_blocked_balance_update", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "3. Cars",
            },
        ),
        migrations.CreateModel(
            name="CarCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="car code"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CarOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "company_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "station_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "profits",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Diesel", "Diesel"),
                            ("Solar", "Solar"),
                            ("Gasoline", "Gasoline"),
                            ("Natural_Gas", "Natural Gas"),
                            ("Electric", "Electric"),
                            ("Hydrogen", "Hydrogen"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("litre", "Litre"),
                            ("unit", "Unit"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "car_meter",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "fuel_consumption_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "motor_image",
                    models.ImageField(blank=True, null=True, upload_to="motor_images/"),
                ),
                (
                    "fuel_image",
                    models.ImageField(blank=True, null=True, upload_to="fuel_images/"),
                ),
                (
                    "car_image",
                    models.ImageField(blank=True, null=True, upload_to="car_images/"),
                ),
            ],
            options={
                "verbose_name": "Car Operation",
                "verbose_name_plural": "5. Car Operations",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "fees",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "1. Companies",
            },
        ),
        migrations.CreateModel(
            name="CompanyBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fees",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "Company Branch",
                "verbose_name_plural": "2. Company Branches",
            },
        ),
        migrations.CreateModel(
            name="CompanyCashRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Cash Request",
                "verbose_name_plural": "6. Company Cash Requests",
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=11)),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="driver code"
                    ),
                ),
                (
                    "lincense_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="driver license number"
                    ),
                ),
                ("lincense_expiration_date", models.DateField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drivers",
                        to="companies.companybranch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver",
                "verbose_name_plural": "4. Drivers",
            },
        ),
    ]
