# Generated by Django 4.2 on 2025-03-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='plate_color',
            field=models.CharField(default='black', max_length=10),
            preserve_default=False,
        ),
    ]
