# Generated by Django 4.2 on 2025-03-13 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='car code')),
                ('plate', models.CharField(max_length=10, verbose_name='car number plate')),
                ('color', models.CharField(max_length=10)),
                ('license_expiration_date', models.DateField()),
                ('model_year', models.IntegerField()),
                ('brand', models.CharField(max_length=25)),
                ('is_with_odometer', models.BooleanField()),
                ('tank_capacity', models.IntegerField()),
                ('permitted_fuel_amount', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=10)),
                ('number_of_fuelings_per_day', models.IntegerField()),
                ('fuel_allowed_days', models.JSONField(blank=True, default=list)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companybranch')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.city')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
