# Generated by Django 4.2 on 2025-06-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="last_meter",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
