# Generated by Django 4.2 on 2025-04-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycashrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In_Progress', 'In Progress'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
