# Generated by Django 4.2 on 2025-06-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="fees",
        ),
        migrations.AddField(
            model_name="car",
            name="last_meter",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="companybranch",
            name="cash_request_fees",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="companybranch",
            name="other_service_fees",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
