# Generated by Django 4.2 on 2025-04-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_companycashrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="companybranch",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
