# Generated by Django 4.2 on 2025-06-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_remove_company_fees_car_last_meter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
