# Generated by Django 4.2 on 2025-03-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_car_fuel_allowed_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_allowed_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
