# Generated by Django 4.2 on 2025-06-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_is_active_alter_company_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Diesel", "Diesel"),
                    ("Solar", "Solar"),
                    ("Gasoline", "Gasoline"),
                    ("Natural_Gas", "Natural Gas"),
                    ("Electric", "Electric"),
                    ("Hydrogen", "Hydrogen"),
                ],
                default="Diesel",
                max_length=20,
                null=True,
            ),
        ),
    ]
