# Generated by Django 4.2 on 2025-04-21 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_alter_car_updated_by_alter_company_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companycashrequest",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
