# Generated by Django 4.2 on 2025-03-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybranch',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
