# Generated by Django 4.2 on 2025-04-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_alter_companycashrequest_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="plate_color",
            field=models.CharField(
                choices=[
                    ("Red", "Red"),
                    ("Blue", "Blue"),
                    ("Orange", "Orange"),
                    ("Yellow", "Yellow"),
                    ("Green", "Green"),
                    ("Gold", "Gold"),
                ],
                max_length=10,
            ),
        ),
    ]
