# Generated by Django 4.2 on 2025-07-17 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0003_stationbranch_cash_request_fees_and_more"),
        ("companies", "0006_companycashrequest_company_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="backup_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backup_service",
                to="stations.service",
            ),
        ),
    ]
