# Generated by Django 4.2 on 2025-08-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_car_backup_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="caroperation",
            name="car_last_meter",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="plate_color",
            field=models.CharField(
                choices=[
                    ("#FF0000", "RED"),
                    ("#0000FF", "BLUE"),
                    ("#FFA500", "ORANGE"),
                    ("#FFFF00", "YELLOW"),
                    ("#008000", "GREEN"),
                    ("#FFD700", "GOLD"),
                ],
                max_length=10,
            ),
        ),
    ]
