# Generated by Django 4.2 on 2025-04-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_caroperation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="plate",
        ),
        migrations.AddField(
            model_name="car",
            name="plate_character",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="car plate character"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="plate_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="car number plate"
            ),
        ),
    ]
