# Generated by Django 4.2 on 2025-08-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_caroperation_car_last_meter_alter_car_plate_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="caroperation",
            old_name="car_last_meter",
            new_name="car_first_meter",
        ),
    ]
