# Generated by Django 4.2 on 2025-05-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_remove_car_plate_car_plate_character_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="fuel_consumption_rate",
            field=models.IntegerField(default=0),
        ),
    ]
