# Generated by Django 4.2 on 2025-09-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_rename_car_last_meter_caroperation_car_first_meter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caroperation",
            name="car_first_meter",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
