# Generated by Django 4.2 on 2025-09-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0010_alter_caroperation_car_first_meter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="last_meter",
            field=models.IntegerField(default=0),
        ),
    ]
