# Generated by Django 4.2 on 2025-05-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0010_car_fuel_consumption_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="examination_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="license_expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
