# Generated by Django 4.2 on 2025-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_alter_car_last_meter"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="next_oil_change_km",
            field=models.IntegerField(
                blank=True, help_text="Next oil change in km", null=True
            ),
        ),
    ]
