# Generated by Django 4.2 on 2025-05-04 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_car_examination_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companybranch",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="companies.company",
            ),
        ),
    ]
