# Generated by Django 4.2 on 2025-10-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_car_next_oil_change_km"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="next_oil_change_km",
            field=models.IntegerField(default=0, help_text="Next oil change in km"),
        ),
    ]
