# Generated by Django 4.2 on 2026-06-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_agent"),
        ("stations", "0004_stationbranch_is_for_landing_page"),
        ("companies", "0013_alter_car_next_oil_change_km"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caroperation",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="companies.car",
            ),
        ),
        migrations.AlterField(
            model_name="caroperation",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="companies.driver",
            ),
        ),
        migrations.AlterField(
            model_name="caroperation",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="stations.service",
            ),
        ),
        migrations.AlterField(
            model_name="caroperation",
            name="station_branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="stations.stationbranch",
            ),
        ),
        migrations.AlterField(
            model_name="caroperation",
            name="worker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="users.worker",
            ),
        ),
    ]
