# Generated by Django 4.2 on 2025-05-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0013_car_oil_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="caroperation",
            name="fuel_consumption_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
