# Generated by Django 4.2 on 2025-05-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0014_caroperation_fuel_consumption_rate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "Car", "verbose_name_plural": "3. Cars"},
        ),
        migrations.AlterModelOptions(
            name="caroperation",
            options={
                "verbose_name": "Car Operation",
                "verbose_name_plural": "5. Car Operations",
            },
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "1. Companies"},
        ),
        migrations.AlterModelOptions(
            name="companybranch",
            options={
                "verbose_name": "Company Branch",
                "verbose_name_plural": "2. Company Branches",
            },
        ),
        migrations.AlterModelOptions(
            name="companycashrequest",
            options={
                "verbose_name": "Company Cash Request",
                "verbose_name_plural": "6. Company Cash Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Driver", "verbose_name_plural": "4. Drivers"},
        ),
        migrations.AlterField(
            model_name="car",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="companycashrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
