# Generated by Django 4.2 on 2026-07-22 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0014_alter_caroperation_car_alter_caroperation_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIApiResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image_size', models.CharField(blank=True, max_length=100, null=True)),
                ('extracted_number', models.CharField(blank=True, max_length=255, null=True)),
                ('token_taken', models.IntegerField(blank=True, null=True)),
                ('estimated_money', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('car_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_api_responses', to='companies.caroperation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI API Response',
                'verbose_name_plural': 'AI API Responses',
            },
        ),
    ]
