# Generated by Django 4.2 on 2025-05-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0005_stationbranchservice"),
        ("companies", "0015_alter_car_options_alter_caroperation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stations.service",
            ),
        ),
    ]
