# Generated by Django 4.2 on 2026-07-25 12:41

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0015_aiapiresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiapiresponse",
            name="match_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
