# Generated by Django 4.2 on 2025-05-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0016_car_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companycashrequest",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_requests",
                to="companies.company",
            ),
        ),
    ]
