# Generated by Django 4.2 on 2026-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_aiapiresponse_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiapiresponse',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aiapiresponse',
            name='request_time',
            field=models.FloatField(blank=True, help_text='API request duration in seconds', null=True),
        ),
    ]
