# Generated by Django 4.2 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0018_alter_aiapiresponse_car_operation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="companybranch",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
