# Generated by Django 4.2 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0019_company_is_available_companybranch_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="balance_source",
            field=models.CharField(
                choices=[
                    ("car", "Car"),
                    ("branch", "Branch"),
                    ("company", "Company"),
                ],
                default="car",
                help_text="من أين يخصم رصيد العمليات: من السيارة أو الفرع أو الشركة",
                max_length=10,
            ),
        ),
    ]
