# Generated by Django 4.2 on 2025-05-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0019_companycashrequest_approved_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("Diesel", "Diesel"),
                    ("Solar", "Solar"),
                    ("Gasoline", "Gasoline"),
                    ("Natural_Gas", "Natural Gas"),
                    ("Electric", "Electric"),
                    ("Hydrogen", "Hydrogen"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="caroperation",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Diesel", "Diesel"),
                    ("Solar", "Solar"),
                    ("Gasoline", "Gasoline"),
                    ("Natural_Gas", "Natural Gas"),
                    ("Electric", "Electric"),
                    ("Hydrogen", "Hydrogen"),
                ],
                default="Diesel",
                max_length=20,
                null=True,
            ),
        ),
    ]
