# Generated by Django 4.2 on 2025-05-29 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0011_alter_service_image"),
        ("companies", "0020_alter_car_fuel_type_alter_caroperation_fuel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="companycashrequest",
            name="station_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stations.stationbranch",
            ),
        ),
    ]
