# Generated by Django 4.2 on 2025-06-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0021_companycashrequest_station_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="companycashrequest",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="companycashrequest",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
