# Generated by Django 4.2 on 2025-06-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0023_alter_caroperation_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caroperation",
            name="cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
