# Generated by Django 4.2 on 2025-06-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0024_alter_caroperation_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caroperation",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="caroperation",
            name="car_meter",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="caroperation",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Diesel", "Diesel"),
                    ("Solar", "Solar"),
                    ("Gasoline", "Gasoline"),
                    ("Natural_Gas", "Natural Gas"),
                    ("Electric", "Electric"),
                    ("Hydrogen", "Hydrogen"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="caroperation",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[("litre", "Litre"), ("unit", "Unit"), ("other", "Other")],
                max_length=20,
                null=True,
            ),
        ),
    ]
