# Generated by Django 4.2 on 2025-06-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0027_companybranch_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caroperation",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
