# Generated by Django 4.2 on 2025-06-11 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0013_stationbranch_fees"),
        ("companies", "0028_alter_caroperation_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caroperation",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operations",
                to="stations.service",
            ),
        ),
    ]
