# Generated by Django 4.2 on 2025-06-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0029_alter_caroperation_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="caroperation",
            name="company_cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="caroperation",
            name="station_cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="caroperation",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
