# Generated by Django 4.2 on 2025-06-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0030_caroperation_company_cost_caroperation_station_cost_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="caroperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
