# Generated by Django 4.2 on 2025-06-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0031_alter_caroperation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caroperation",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
