# Generated by Django 4.2 on 2025-06-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0032_alter_caroperation_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="caroperation",
            name="profits",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="caroperation",
            name="car_meter",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="caroperation",
            name="fuel_consumption_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
