# Generated by Django 4.2 on 2025-06-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0033_caroperation_profits_alter_caroperation_car_meter_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="is_blocked_balance_update",
            field=models.BooleanField(default=False),
        ),
    ]
