# Generated by Django 4.2 on 2025-06-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0034_car_is_blocked_balance_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="caroperation",
            name="car_image",
            field=models.ImageField(blank=True, null=True, upload_to="car_images/"),
        ),
    ]
