# Generated by Django 4.2 on 2025-03-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="unit",
            field=models.CharField(
                choices=[("litre", "Litre"), ("unit", "Unit"), ("other", "Other")],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=25),
        ),
    ]
