# Generated by Django 4.2 on 2025-03-22 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_station_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationservice',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_services', to='stations.station'),
        ),
    ]
