# Generated by Django 4.2 on 2025-08-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0003_stationbranch_cash_request_fees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationbranch",
            name="is_for_landing_page",
            field=models.BooleanField(default=False),
        ),
    ]
