# Generated by Django 4.2 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0005_alter_service_created_by_alter_service_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="stationbranch",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
