# Generated by Django 4.2 on 2025-05-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0006_stationbranch_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
