# Generated by Django 4.2 on 2025-05-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0007_station_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stationbranch",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="stations.station",
            ),
        ),
    ]
