# Generated by Django 4.2 on 2025-05-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0008_alter_stationbranch_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="service_images/"),
        ),
    ]
