# Generated by Django 4.2 on 2025-05-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0009_service_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stationbranchservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="station_branch_services",
                to="stations.service",
            ),
        ),
    ]
