# Generated by Django 4.2 on 2025-05-15 16:28

import apps.stations.models.service_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0010_alter_stationbranchservice_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="service_images/",
                validators=[apps.stations.models.service_models.validate_image_or_svg],
            ),
        ),
    ]
