# Generated by Django 4.2 on 2025-06-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0011_alter_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="fees",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
