# Generated by Django 4.2 on 2025-06-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0012_station_fees"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationbranch",
            name="fees",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
