# Generated by Django 4.2 on 2025-05-04 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0012_alter_companybranch_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stations", "0005_stationbranchservice"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="KhaznaTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "is_incoming",
                    models.BooleanField(
                        help_text="True if money came into the khazna;False if it went out."
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_by", models.JSONField(blank=True, default=list)),
                (
                    "reference_code",
                    models.CharField(
                        help_text="If there was invoice or receipt code",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("bank", "Bank"),
                            ("instapay", "Instapay"),
                            ("cash", "Cash"),
                            ("wallet", "Wallet"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="kazna_transaction_photos/"
                    ),
                ),
                (
                    "is_unpaid",
                    models.BooleanField(
                        default=False,
                        help_text="True if the transaction hasn't been paid yet.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StationKhaznaTransaction",
            fields=[
                (
                    "khaznatransaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounting.khaznatransaction",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Station Khazna Transaction",
                "verbose_name_plural": "Station Khazna Transactions",
            },
            bases=("accounting.khaznatransaction",),
        ),
        migrations.CreateModel(
            name="CompanyKhaznaTransaction",
            fields=[
                (
                    "khaznatransaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounting.khaznatransaction",
                    ),
                ),
                (
                    "for_what",
                    models.CharField(
                        choices=[("Branch", "Branch"), ("Car", "Car")],
                        default="Branch",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Khazna Transaction",
                "verbose_name_plural": "Company Khazna Transactions",
            },
            bases=("accounting.khaznatransaction",),
        ),
    ]
