# Generated by Django 4.2 on 2025-07-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companykhaznatransaction",
            name="for_what",
            field=models.CharField(
                blank=True,
                choices=[("Branch", "Branch"), ("Car", "Car"), ("Driver", "Driver")],
                default="Branch",
                max_length=20,
                null=True,
            ),
        ),
    ]
