# Generated by Django 4.2 on 2025-05-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_khaznatransaction_polymorphic_ctype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="khaznatransaction",
            name="polymorphic_ctype",
        ),
    ]
