# Generated by Django 4.2 on 2026-06-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0004_stationbranch_is_for_landing_page"),
        ("companies", "0014_alter_caroperation_car_alter_caroperation_driver_and_more"),
        ("accounting", "0003_alter_companykhaznatransaction_for_what"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companykhaznatransaction",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="companies.company"
            ),
        ),
        migrations.AlterField(
            model_name="companykhaznatransaction",
            name="company_branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.companybranch",
            ),
        ),
        migrations.AlterField(
            model_name="stationkhaznatransaction",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="stations.station"
            ),
        ),
        migrations.AlterField(
            model_name="stationkhaznatransaction",
            name="station_branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stations.stationbranch",
            ),
        ),
    ]
