# Generated by Django 4.2 on 2025-05-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_companykhaznatransaction_for_what"),
    ]

    operations = [
        migrations.AddField(
            model_name="khaznatransaction",
            name="is_internal",
            field=models.BooleanField(
                default=False, help_text="True if the transaction is internal."
            ),
        ),
    ]
