# Generated by Django 4.2 on 2025-05-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_khaznatransaction_is_internal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="khaznatransaction",
            name="is_incoming",
            field=models.BooleanField(
                blank=True,
                help_text="True if money came into the khazna;False if it went out.",
                null=True,
            ),
        ),
    ]
