# Generated by Django 4.2 on 2025-05-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0019_companycashrequest_approved_by"),
        ("stations", "0011_alter_service_image"),
        ("accounting", "0007_alter_khaznatransaction_is_incoming"),
    ]

    operations = [
        migrations.AddField(
            model_name="companykhaznatransaction",
            name="company_branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.companybranch",
            ),
        ),
        migrations.AddField(
            model_name="stationkhaznatransaction",
            name="station_branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stations.stationbranch",
            ),
        ),
    ]
