# Generated by Django 4.2 on 2025-05-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfigrationsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term_conditions", models.TextField()),
                ("privacy_policy", models.TextField()),
                ("about_us", models.TextField()),
                ("faq", models.TextField()),
            ],
        ),
    ]
