# Generated by Django 4.2 on 2025-05-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configrationsmodel",
            name="app_version",
            field=models.CharField(default="1.0.0", max_length=255),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="company_support_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="company_support_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="company_support_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="company_support_phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="station_support_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="station_support_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="station_support_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="station_support_phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
