# Generated by Django 4.2 on 2025-08-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configrations", "0002_configrationsmodel_app_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="")),
                ("order", models.IntegerField(default=0)),
            ],
        ),
    ]
