# Generated by Django 4.2 on 2025-10-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configrations", "0003_slider"),
    ]

    operations = [
        migrations.AddField(
            model_name="configrationsmodel",
            name="facebook_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="instagram_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="linkedin_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="telegram_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="twitter_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="x_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="youtube_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
