# Generated by Django 4.2 on 2025-10-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configrations", "0004_configrationsmodel_facebook_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
