# Generated by Django 4.2 on 2025-10-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configrations", "0005_slider_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configrationsmodel",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
