# Generated by Django 4.2 on 2025-11-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configrations", "0006_alter_configrationsmodel_whatsapp_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="configrationsmodel",
            name="android_app_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configrationsmodel",
            name="ios_app_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
