# Generated by Django 4.2 on 2025-03-22 18:56

import apps.users.v1.managements
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('company_owner', 'Companyowner'), ('company_branch_manager', 'Companybranchmanager'), ('driver', 'Driver'), ('station_manager', 'Stationmanager'), ('station_employee', 'Stationemployee'), ('station_worker', 'Stationworker')], default='admin', max_length=25),
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Owner',
                'verbose_name_plural': 'Company Owners',
            },
            bases=('users.user', models.Model),
            managers=[
                ('objects', apps.users.v1.managements.CustomUserManager()),
            ],
        ),
    ]
