# Generated by Django 4.2 on 2025-07-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("finance", "Finance"),
                    ("customer_support", "Customersupport"),
                    ("company_owner", "Companyowner"),
                    ("company_branch_manager", "Companybranchmanager"),
                    ("driver", "Driver"),
                    ("station_owner", "Stationowner"),
                    ("station_branch_manager", "Stationbranchmanager"),
                    ("station_worker", "Stationworker"),
                ],
                default="admin",
                max_length=25,
            ),
        ),
    ]
