# Generated by Django 4.2 on 2025-04-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_firebasetoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="firebasetoken",
            old_name="created_at",
            new_name="created",
        ),
    ]
