# Generated by Django 4.2 on 2025-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_created_at_firebasetoken_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_password_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_password_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
