# Generated by Django 4.2 on 2025-11-03 15:02

import apps.users.v1.managements
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "district",
                    models.ManyToManyField(
                        related_name="supervisors", to="geo.district"
                    ),
                ),
            ],
            options={
                "verbose_name": "Supervisor",
                "verbose_name_plural": "Supervisors",
            },
            bases=("users.user",),
            managers=[
                ("objects", apps.users.v1.managements.CustomUserManager()),
            ],
        ),
    ]
