# Generated by Django 4.2 on 2025-03-26 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_companybranchmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybranchmanager',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_branch_managers', to='users.companyuser'),
        ),
    ]
