# Generated by Django 4.2 on 2025-04-18 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_reset_password_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companybranchmanager",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
