# Generated by Django 4.2 on 2026-08-16 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0018_alter_aiapiresponse_car_operation_and_more"),
        ("stations", "0005_alter_service_created_by_alter_service_updated_by_and_more"),
        ("users", "0005_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="team_head",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agents",
                to="users.supervisor",
            ),
        ),
        migrations.AlterField(
            model_name="companybranchmanager",
            name="company_branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managers",
                to="companies.companybranch",
            ),
        ),
        migrations.AlterField(
            model_name="companybranchmanager",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="companybranchmanager",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="companyuser",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owners",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="stationbranchmanager",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stationbranchmanager",
            name="station_branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managers",
                to="stations.stationbranch",
            ),
        ),
        migrations.AlterField(
            model_name="stationbranchmanager",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stationbranchmanager",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="station_branch_managers",
                to="users.stationowner",
            ),
        ),
        migrations.AlterField(
            model_name="stationowner",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owners",
                to="stations.station",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="station_branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workers",
                to="stations.stationbranch",
            ),
        ),
    ]
