# Generated by Django 4.2 on 2026-09-15 06:58

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_agent_team_head_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupport',
            fields=[
            ],
            options={
                'verbose_name': 'Customer Support',
                'verbose_name_plural': 'Customer Support',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', apps.users.models.CustomerSupportManager()),
            ],
        ),
    ]
