# Generated by Django 4.2 on 2025-05-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stationbranchmanager",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="station_branch_managers",
                to="users.stationowner",
            ),
        ),
    ]
