# Generated by Django 4.2 on 2025-05-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_stationbranchmanager_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StationBranchManager",
        ),
    ]
