import math
from decimal import Decimal

from django.db import models, transaction

from apps.accounting.helpers import (
    generate_company_transaction,
    generate_station_transaction,
)
from apps.accounting.models import KhaznaTransaction
from apps.companies.models.company_models import Car
from apps.companies.models.operation_model import CarOperation
from apps.notifications.models import Notification
from apps.stations.models.stations_models import StationBranch
from apps.users.models import CompanyUser, StationOwner, User

# `created`/`modified` are auto-managed by TimeStampedModel and
# `created_by`/`updated_by` belong to the admin doing the clone, so none of them
# are carried over. `code` is regenerated by CarOperation.save().
EXCLUDED_CLONE_FIELDS = frozenset(
    {"id", "created", "modified", "created_by", "updated_by", "code"}
)

HUNDRED = Decimal("100")


class CloneError(Exception):
    """The source operation cannot be cloned with the requested amount."""


def as_decimal(value):
    """Decimal fields can still hold floats before a refresh from the db."""
    return value if isinstance(value, Decimal) else Decimal(str(value))


def clone_note(source_code):
    """Arabic note appended to every record the clone generates."""
    return f"نسخة من العملية رقم {source_code}"


def company_liter_cost_for(service, company_branch):
    """Litre price charged to the company: service cost plus the branch fees."""
    service_cost = as_decimal(service.cost)
    return service_cost * (as_decimal(company_branch.fees) / HUNDRED) + service_cost


def available_liters_for(car, company_liter_cost):
    """Litres the car can still take, capped by its tank and its balance."""
    tank_capacity = car.permitted_fuel_amount or car.tank_capacity
    affordable = math.floor(as_decimal(car.available_balance) / company_liter_cost)
    return min(tank_capacity, affordable)


def calculate_costs(*, amount, service, company_branch, station_branch):
    """The same money formulas CreateCarOperationSerializer applies."""
    amount = as_decimal(amount)
    service_cost = as_decimal(service.cost)
    cost = round(amount * service_cost, 2)
    company_cost = round(
        amount * company_liter_cost_for(service, company_branch), 2
    )
    station_cost = round(
        amount * (service_cost + as_decimal(station_branch.fees)), 2
    )
    return {
        "cost": cost,
        "company_cost": company_cost,
        "station_cost": station_cost,
        "profits": round(company_cost - station_cost, 2),
    }


def build_clone(source, overrides, user):
    """A brand new CarOperation carrying every stored field of `source`."""
    clone = CarOperation()
    for field in CarOperation._meta.concrete_fields:
        if field.attname in EXCLUDED_CLONE_FIELDS:
            continue
        value = getattr(source, field.attname)
        if isinstance(field, models.FileField):
            # keep the stored path rather than the source-bound FieldFile
            value = value.name
        setattr(clone, field.attname, value)

    for attribute, value in overrides.items():
        setattr(clone, attribute, value)

    clone.created_by = user
    clone.updated_by = user
    return clone


def notify(user_ids, message):
    # created one by one on purpose: the post_save signal on Notification is
    # what pushes the FCM message, and bulk_create would skip it
    for user_id in user_ids:
        Notification.objects.create(
            user_id=user_id,
            title=message,
            description=message,
            type=Notification.NotificationType.MONEY,
        )


def station_notification_users(station_id, station_branch_id, worker_id):
    user_ids = list(
        StationOwner.objects.filter(
            station_id=station_id, role=StationOwner.UserRoles.StationOwner
        ).values_list("id", flat=True)
    )
    user_ids.extend(
        StationOwner.objects.filter(
            station_id=station_id,
            role=User.UserRoles.StationBranchManager,
            station_branch_managers__station_branch=station_branch_id,
        ).values_list("id", flat=True)
    )
    user_ids.append(worker_id)
    return user_ids


def company_notification_users(company_id, company_branch_id):
    user_ids = list(
        CompanyUser.objects.filter(
            company_id=company_id, role=CompanyUser.UserRoles.CompanyOwner
        ).values_list("id", flat=True)
    )
    user_ids.extend(
        CompanyUser.objects.filter(
            company_id=company_id,
            role=CompanyUser.UserRoles.CompanyBranchManager,
            company_branch_managers__company_branch=company_branch_id,
        ).values_list("id", flat=True)
    )
    return user_ids


def apply_financial_effects(*, clone, car, station_branch, note, user):
    """
    Mirrors the completed-operation side effects of the create flow: both
    khazna transactions, both balances and the two notification fan-outs.
    """
    fueling_message = (
        f"تم تفويل سيارة رقم {car.plate} بعدد {clone.amount} لتر"
    )
    description = f"{fueling_message} - {note}"

    generate_station_transaction(
        station_id=station_branch.station_id,
        station_branch_id=station_branch.id,
        amount=clone.station_cost,
        status=KhaznaTransaction.TransactionStatus.APPROVED,
        description=description,
        created_by_id=user.id,
        is_internal=False,
    )
    station_branch.balance = as_decimal(station_branch.balance) - clone.station_cost
    station_branch.save(update_fields=["balance"])

    notify(
        station_notification_users(
            station_branch.station_id, station_branch.id, clone.worker_id
        ),
        fueling_message,
    )

    company_branch = car.branch
    generate_company_transaction(
        company_id=company_branch.company_id,
        company_branch_id=company_branch.id,
        amount=clone.company_cost,
        status=KhaznaTransaction.TransactionStatus.APPROVED,
        description=description,
        created_by_id=user.id,
        is_internal=True,
    )

    notify(
        company_notification_users(company_branch.company_id, company_branch.id),
        (
            f"{fueling_message} "
            f"وخصم مبلغ بمقدار {clone.company_cost:.2f} جنية"
        ),
    )


@transaction.atomic
def clone_car_operation(*, source, amount, user):
    """
    Duplicate `source` with a new `amount`, recalculating every money field.

    Meter readings are copied as they were recorded: the car odometer already
    moved past them, so re-deriving them from the car would be wrong.
    """
    if source.service_id is None:
        raise CloneError("لا يمكن نسخ عملية بدون خدمة لأنه لا يمكن إعادة حساب التكلفة.")

    if amount is None:
        raise CloneError("الكمية يجب أن تكون أكبر من صفر.")

    amount = as_decimal(amount)
    if amount <= 0:
        raise CloneError("الكمية يجب أن تكون أكبر من صفر.")

    # locked for the whole transaction so concurrent operations cannot both
    # read the same balance and overwrite each other's deduction
    car = Car.objects.select_for_update().select_related("branch").get(pk=source.car_id)
    station_branch = (
        StationBranch.objects.select_for_update()
        .get(pk=source.worker.station_branch_id)
    )
    service = source.service

    available_liters = available_liters_for(
        car, company_liter_cost_for(service, car.branch)
    )
    if amount > available_liters:
        raise CloneError(f"الكمية المطلوبة اكبر من الحد الأقصى {available_liters}")

    costs = calculate_costs(
        amount=amount,
        service=service,
        company_branch=car.branch,
        station_branch=station_branch,
    )
    clone = build_clone(source, {"amount": amount, **costs}, user)
    clone.save()

    if clone.status == CarOperation.OperationStatus.COMPLETED:
        car.deduct_balance(clone.company_cost)
        apply_financial_effects(
            clone=clone,
            car=car,
            station_branch=station_branch,
            note=clone_note(source.code),
            user=user,
        )

    return clone
