# Generated by Django 4.2 on 2025-04-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_success",
            field=models.BooleanField(default=False),
        ),
    ]
