# Generated by Django 4.2 on 2025-04-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_is_success"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("fuel", "Fuel"), ("money", "Money"), ("general", "General")],
                max_length=20,
            ),
        ),
    ]
