# Generated by Django 4.2 on 2025-05-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
