# Generated by Django 4.2 on 2025-05-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notification_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("fuel", "Fuel"),
                    ("money", "Money"),
                    ("general", "General"),
                    ("station_worker", "Station Worker"),
                    ("station_service", "Station Service"),
                ],
                max_length=20,
            ),
        ),
    ]
